Amanda         | Email: Sun.amanda26@gmail.com      | Kill Count: 0   
Angela         | Email: aw123abc@gmail.com          | Kill Count: 3   
Annie          | Email: zhangannie0@gmail.com       | Kill Count: 0   
Bivi           | Email: biviana_lie@outlook.com     | Kill Count: 0   
Byron          | Email: byronc@ucla.edu             | Kill Count: 0   
Davey          | Email: notwdjw@gmail.com           | Kill Count: 0   
Deborah        | Email: debcheng3@gmail.com         | Kill Count: 1   
EthanKato      | Email: ethankato@g.ucla.edu        | Kill Count: 0   
Grace          | Email: grace.jf.lily@gmail.com     | Kill Count: 0   
Griffin        | Email: Gsukarto@gmail.com          | Kill Count: 0   
HannahLiu      | Email: Hannah.h.liu98@gmail.com    | Kill Count: 0   
HannahPham     | Email: hannah.pham@gmail.com       | Kill Count: 1   
Ingrid         | Email: iywu11@gmail.com            | Kill Count: 0   
Isabel         | Email: Isabelchu123@gmail.com      | Kill Count: 0   
JOel           | Email: jrmashita@ucla.edu          | Kill Count: 0   
JasonLeung     | Email: leung.jasonh@gmail.com      | Kill Count: 1   
JasonLiu       | Email: jason.sean.liu@gmail.com    | Kill Count: 1   
Jeffrey        | Email: jeffrey7221@gmail.com       | Kill Count: 0   
Jennifer       | Email: jenlin5368@gmail.com        | Kill Count: 0   
Jenny          | Email: jey.truong@gmail.com        | Kill Count: 0   
Jeremy         | Email: jeremiah.fan@gmail.com      | Kill Count: 0   
Jerry          | Email: jerryklai@gmail.com         | Kill Count: 1   
Jlam           | Email: jlam1999@g.ucla.edu         | Kill Count: 2   
JonathanTse    | Email: jt.whirlpoolgalaxy@gmail.com| Kill Count: 1   
Jordan         | Email: jordan@leongfamily.us       | Kill Count: 1   
Joseph         | Email: josephyu612@gmail.com       | Kill Count: 0   
JoshYu         | Email: joshuayu12@gmail.com        | Kill Count: 0   
JoshuaWidjaja  | Email: jnwidjaja@gmail.com         | Kill Count: 1   
Katie          | Email: ktlam99@gmail.com           | Kill Count: 3   
Kaylee         | Email: Kayleesiu24@gmail.com       | Kill Count: 0   
Kimberly       | Email: kimberlyh.hoops31@gmail.com | Kill Count: 0   
Kristee        | Email: Kristee.song@gmail.com      | Kill Count: 0   
Lam            | Email: lpham127@gmail.com          | Kill Count: 0   
Leo            | Email: siow98@ucla.edu             | Kill Count: 0   
Lindsey        | Email: lollipoplinz@gmail.com      | Kill Count: 0   
Lulu           | Email: Wenxinfan98@gmail.com       | Kill Count: 0   
Mandi          | Email: mandiahn@yahoo.com          | Kill Count: 0   
Mark           | Email: markdong413@yahoo.com       | Kill Count: 0   
Michelle       | Email: michelle.chungg@gmail.com   | Kill Count: 1   
Nateney        | Email: nney78@gmail.com            | Kill Count: 0   
Nathan         | Email: nwtsai@gmail.com            | Kill Count: 0   
Nick           | Email: nicklin369@gmail.com        | Kill Count: 1   
Rebekah        | Email: rebekah.park.12@gmail.com   | Kill Count: 0   
Reid           | Email: reidmasaki20@gmail.com      | Kill Count: 0   
Reine          | Email: reine.naka@gmail.com        | Kill Count: 0   
Ryan           | Email: ryan.k.cheng@gmail.com      | Kill Count: 0   
Scott          | Email: imakawakami@gmail.com       | Kill Count: 1   
Steffi         | Email: yeokts@gmail.com            | Kill Count: 0   
Steven         | Email: Stev1612@gmail.com          | Kill Count: 0   
SydneyK        | Email: sydneyk98@gmail.com         | Kill Count: 0   
Timothy        | Email: timothyli97@gmail.com       | Kill Count: 1   
Tina           | Email: li.tina.grace@gmail.com     | Kill Count: 0   
